import "./globals.css";

import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import localFont from "next/font/local";
import { cookies } from "next/headers";

import { CallSignalingProvider } from "@/entities/call/model/CallSignalingProvider";
import { SITE_TITLE } from "@/shared/lib/constants/siteInfo";
import { AuthProvider } from "@/shared/providers/authProvider";
import { IsMobileProvider } from "@/shared/providers/isMobileProvider";
import { WSProvider } from "@/shared/providers/wsProvider";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["cyrillic", "latin"],
});

export const metadata: Metadata = {
  title: `${SITE_TITLE}`,
  description: "Generated by create next app",
};

export const appleColorEmoji = localFont({
  src: "./fonts/Emoji-subset.woff2",
  weight: "400",
  style: "normal",
  display: "swap",
  variable: "--font-apple-color-emoji",
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get("accessToken")?.value || null;
  return (
    <html lang="ru">
      <body className={`${roboto.variable} ${appleColorEmoji.variable} font-sans antialiased`}>
        <AuthProvider initialToken={token}>
          <WSProvider>
            <CallSignalingProvider>
              <IsMobileProvider>{children}</IsMobileProvider>
            </CallSignalingProvider>
          </WSProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
